blank_issues_enabled: true
contact_links:
  - name: Use CLI Scripts (Recommended)
    url: https://github.com/your-repo/docs
    about: We recommend using the CLI scripts for creating issues (./scripts/create-feature-issue.sh)
